require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'report_builder'

Cucumber::Rake::Task.new(:features) do |t|
   t.cucumber_opts = "--color --format pretty --format json -o 'output/cucumber_json' --require features/"
end

task :report do
  ReportBuilder.input_path = 'output/cucumber_json'

   ReportBuilder.configure do |config|
     config.report_path = 'reports/my_test_report'
     config.report_types = [:json, :html]
   end

  options = {
      report_title: 'My Test Results'
  }

  ReportBuilder.build_report options
end

task :default => :features
task :generate => :report
